from fastapi import FastAPI

from app.methods.collection import (
    GetRootCollectionPermissionsArgs,
    MoveCollectionsResult,
    create_collection,
    delete_collection,
    delete_collections,
    get_collection,
    get_collection_breadcrumbs,
    get_collection_content,
    get_collections_by_ids,
    get_root_collection_permissions,
    move_collection,
    move_collections,
    update_collection,
)
from app.methods.data import get_chart_data, get_dataset_field_values, query_dataset
from app.methods.connection import (
    create_connection,
    delete_connection,
    get_connection,
    update_connection,
)
from app.methods.dashboard import (
    create_dashboard,
    delete_dashboard,
    get_dashboard,
    update_dashboard,
)
from app.methods.dataset import (
    create_dataset,
    delete_dataset,
    get_dataset,
    update_dataset,
    validate_dataset,
    validate_dataset_formula,
)
from app.methods.entries import (
    get_entries_permissions,
    get_entries_relations,
    rename_entry,
)
from app.methods.folder import (
    DeleteFolderResult,
    create_folder,
    delete_folder,
    get_permissions,
    move_folder_entry,
)
from app.methods.navigation import get_entries, list_directory
from app.methods.ql import (
    create_ql_chart,
    delete_ql_chart,
    get_ql_chart,
    update_ql_chart,
)
from app.methods.wizard import (
    create_wizard_chart,
    delete_wizard_chart,
    get_wizard_chart,
    update_wizard_chart,
)
from app.methods.workbook import (
    WorkbooksBulkResult,
    create_workbook,
    delete_workbook,
    delete_workbooks,
    get_workbook,
    get_workbook_entries,
    get_workbooks_by_ids,
    get_workbooks_list,
    move_workbook,
    move_workbooks,
    update_workbook,
)
from app.methods.workbook_export import (
    cancel_workbook_export,
    get_workbook_export_result,
    get_workbook_export_status,
    start_workbook_export,
)
from app.methods.workbook_import import (
    get_workbook_import_status,
    start_workbook_import,
)
from app.models.generated import (
    Collection,
    ConnectionCreate,
    ConnectionRead,
    DatasetCreate,
    DatasetRead,
    CreateCollectionArgs,
    CreateCollectionResult,
    CreateConnectionResult,
    CreateDashboardV1Args,
    DeleteDashboardArgs,
    GetDashboardV1Args,
    GetDashboardV1Result,
    UpdateDashboardV1Args,
    CreateFolderArgs,
    CreateFolderResult,
    CreateQLChartArgs,
    CreateWizardChartArgs,
    CancelWorkbookExportArgs,
    CancelWorkbookExportResult,
    CreateWorkbookArgs,
    CreateWorkbookResult,
    DeleteCollectionArgs,
    DeleteCollectionResult,
    DeleteCollectionsArgs,
    DeleteCollectionsResult,
    DeleteFolderArgs,
    DeleteQLChartArgs,
    DeleteWizardChartArgs,
    DeleteWorkbookArgs,
    DeleteWorkbooksArgs,
    GetCollectionArgs,
    GetCollectionBreadcrumbsArgs,
    GetCollectionBreadcrumbsResult,
    GetCollectionResult,
    GetCollectionsByIdsArgs,
    GetEntriesPermissionsArgs,
    GetEntriesPermissionsResult,
    GetEntriesRelationsArgs,
    GetEntriesRelationsResult,
    GetEntriesV2Args,
    GetEntriesV2Result,
    GetPermissionsArgs,
    GetPermissionsResult,
    GetRootCollectionPermissionsResult,
    GetStructureItemsArgs,
    GetStructureItemsResult,
    GetQLChartArgs,
    GetWizardChartArgs,
    StartWorkbookExportArgs,
    StartWorkbookExportResult,
    StartWorkbookImportArgs,
    StartWorkbookImportResult,
    GetWorkbookImportStatusArgs,
    GetWorkbookImportStatusResult,
    GetWorkbookArgs,
    GetWorkbookEntriesArgs,
    GetWorkbookEntriesResult,
    GetWorkbookExportResultArgs,
    GetWorkbookExportResultResult,
    GetWorkbookExportStatusArgs,
    GetWorkbookExportStatusResult,
    GetWorkbookResult,
    GetWorkbooksByIdsArgs,
    GetWorkbooksListArgs,
    GetWorkbooksListResult,
    ListDirectoryArgs,
    ListDirectoryResult,
    MoveCollectionArgs,
    MoveCollectionsArgs,
    MoveEntryArgs,
    MoveEntryResult,
    MoveWorkbookArgs,
    MoveWorkbooksArgs,
    RenameEntryArgs,
    RenameEntryResult,
    UpdateCollectionArgs,
    UpdateQLChartArgs,
    UpdateWizardChartArgs,
    UpdateWorkbookArgs,
    Workbook,
)
from app.models.rpc_data import (
    GetChartDataArgs,
    GetChartDataResult,
    GetDatasetFieldValuesArgs,
    GetDatasetFieldValuesResult,
    QueryDatasetArgs,
    QueryDatasetResult,
)
from app.models.rpc_bi import (
    ChartResult,
    DeleteConnectionArgs,
    DeleteDatasetArgs,
    EmptyResult,
    GetConnectionArgs,
    GetDatasetArgs,
    UpdateConnectionArgs,
    UpdateDatasetArgs,
    ValidateDatasetArgs,
    ValidateDatasetFormulaArgs,
    ValidateDatasetFormulaResult,
)
from app.registry import register_rpc


def register_all(app: FastAPI) -> None:
    register_rpc(
        app,
        "createCollection",
        CreateCollectionArgs,
        CreateCollectionResult,
        create_collection,
    )
    register_rpc(
        app,
        "getCollection",
        GetCollectionArgs,
        GetCollectionResult,
        get_collection,
    )
    register_rpc(
        app,
        "updateCollection",
        UpdateCollectionArgs,
        Collection,
        update_collection,
    )
    register_rpc(
        app,
        "deleteCollection",
        DeleteCollectionArgs,
        DeleteCollectionResult,
        delete_collection,
    )
    register_rpc(
        app,
        "deleteCollections",
        DeleteCollectionsArgs,
        DeleteCollectionsResult,
        delete_collections,
    )
    register_rpc(
        app,
        "moveCollection",
        MoveCollectionArgs,
        Collection,
        move_collection,
    )
    register_rpc(
        app,
        "moveCollections",
        MoveCollectionsArgs,
        MoveCollectionsResult,
        move_collections,
    )
    register_rpc(
        app,
        "getCollectionsByIds",
        GetCollectionsByIdsArgs,
        list[Collection],
        get_collections_by_ids,
    )
    register_rpc(
        app,
        "getCollectionContent",
        GetStructureItemsArgs,
        GetStructureItemsResult,
        get_collection_content,
    )
    register_rpc(
        app,
        "getCollectionBreadcrumbs",
        GetCollectionBreadcrumbsArgs,
        GetCollectionBreadcrumbsResult,
        get_collection_breadcrumbs,
    )
    register_rpc(
        app,
        "getRootCollectionPermissions",
        GetRootCollectionPermissionsArgs,
        GetRootCollectionPermissionsResult,
        get_root_collection_permissions,
    )
    register_rpc(
        app,
        "getWorkbooksList",
        GetWorkbooksListArgs,
        GetWorkbooksListResult,
        get_workbooks_list,
    )
    register_rpc(
        app,
        "createWorkbook",
        CreateWorkbookArgs,
        CreateWorkbookResult,
        create_workbook,
    )
    register_rpc(
        app,
        "getWorkbook",
        GetWorkbookArgs,
        GetWorkbookResult,
        get_workbook,
    )
    register_rpc(
        app,
        "updateWorkbook",
        UpdateWorkbookArgs,
        Workbook,
        update_workbook,
    )
    register_rpc(
        app,
        "deleteWorkbook",
        DeleteWorkbookArgs,
        Workbook,
        delete_workbook,
    )
    register_rpc(
        app,
        "deleteWorkbooks",
        DeleteWorkbooksArgs,
        WorkbooksBulkResult,
        delete_workbooks,
    )
    register_rpc(
        app,
        "moveWorkbook",
        MoveWorkbookArgs,
        Workbook,
        move_workbook,
    )
    register_rpc(
        app,
        "moveWorkbooks",
        MoveWorkbooksArgs,
        WorkbooksBulkResult,
        move_workbooks,
    )
    register_rpc(
        app,
        "getWorkbooksByIds",
        GetWorkbooksByIdsArgs,
        list[Workbook],
        get_workbooks_by_ids,
    )
    register_rpc(
        app,
        "getWorkbookEntries",
        GetWorkbookEntriesArgs,
        GetWorkbookEntriesResult,
        get_workbook_entries,
    )
    register_rpc(
        app,
        "getEntriesRelations",
        GetEntriesRelationsArgs,
        GetEntriesRelationsResult,
        get_entries_relations,
    )
    register_rpc(
        app,
        "renameEntry",
        RenameEntryArgs,
        RenameEntryResult,
        rename_entry,
    )
    register_rpc(
        app,
        "getEntriesPermissions",
        GetEntriesPermissionsArgs,
        GetEntriesPermissionsResult,
        get_entries_permissions,
    )
    register_rpc(
        app,
        "getEntries",
        GetEntriesV2Args,
        GetEntriesV2Result,
        get_entries,
    )
    register_rpc(
        app,
        "listDirectory",
        ListDirectoryArgs,
        ListDirectoryResult,
        list_directory,
    )
    register_rpc(
        app,
        "createFolder",
        CreateFolderArgs,
        CreateFolderResult,
        create_folder,
    )
    register_rpc(
        app,
        "deleteFolder",
        DeleteFolderArgs,
        DeleteFolderResult,
        delete_folder,
    )
    register_rpc(
        app,
        "moveFolderEntry",
        MoveEntryArgs,
        MoveEntryResult,
        move_folder_entry,
    )
    register_rpc(
        app,
        "getPermissions",
        GetPermissionsArgs,
        GetPermissionsResult,
        get_permissions,
    )
    register_rpc(
        app,
        "createConnection",
        ConnectionCreate,
        CreateConnectionResult,
        create_connection,
    )
    register_rpc(
        app,
        "getConnection",
        GetConnectionArgs,
        ConnectionRead,
        get_connection,
    )
    register_rpc(
        app,
        "updateConnection",
        UpdateConnectionArgs,
        EmptyResult,
        update_connection,
    )
    register_rpc(
        app,
        "deleteConnection",
        DeleteConnectionArgs,
        EmptyResult,
        delete_connection,
    )
    register_rpc(
        app,
        "createDataset",
        DatasetCreate,
        DatasetRead,
        create_dataset,
    )
    register_rpc(
        app,
        "getDataset",
        GetDatasetArgs,
        DatasetRead,
        get_dataset,
    )
    register_rpc(
        app,
        "updateDataset",
        UpdateDatasetArgs,
        DatasetRead,
        update_dataset,
    )
    register_rpc(
        app,
        "deleteDataset",
        DeleteDatasetArgs,
        EmptyResult,
        delete_dataset,
    )
    register_rpc(
        app,
        "validateDataset",
        ValidateDatasetArgs,
        DatasetRead,
        validate_dataset,
    )
    register_rpc(
        app,
        "validateDatasetFormula",
        ValidateDatasetFormulaArgs,
        ValidateDatasetFormulaResult,
        validate_dataset_formula,
    )
    register_rpc(
        app,
        "createDashboard",
        CreateDashboardV1Args,
        GetDashboardV1Result,
        create_dashboard,
    )
    register_rpc(
        app,
        "getDashboard",
        GetDashboardV1Args,
        GetDashboardV1Result,
        get_dashboard,
    )
    register_rpc(
        app,
        "updateDashboard",
        UpdateDashboardV1Args,
        GetDashboardV1Result,
        update_dashboard,
    )
    register_rpc(
        app,
        "deleteDashboard",
        DeleteDashboardArgs,
        EmptyResult,
        delete_dashboard,
    )
    register_rpc(
        app,
        "createWizardChart",
        CreateWizardChartArgs,
        ChartResult,
        create_wizard_chart,
    )
    register_rpc(
        app,
        "getWizardChart",
        GetWizardChartArgs,
        ChartResult,
        get_wizard_chart,
    )
    register_rpc(
        app,
        "updateWizardChart",
        UpdateWizardChartArgs,
        ChartResult,
        update_wizard_chart,
    )
    register_rpc(
        app,
        "deleteWizardChart",
        DeleteWizardChartArgs,
        EmptyResult,
        delete_wizard_chart,
    )
    register_rpc(
        app,
        "createQLChart",
        CreateQLChartArgs,
        ChartResult,
        create_ql_chart,
    )
    register_rpc(
        app,
        "getQLChart",
        GetQLChartArgs,
        ChartResult,
        get_ql_chart,
    )
    register_rpc(
        app,
        "updateQLChart",
        UpdateQLChartArgs,
        ChartResult,
        update_ql_chart,
    )
    register_rpc(
        app,
        "deleteQLChart",
        DeleteQLChartArgs,
        EmptyResult,
        delete_ql_chart,
    )
    register_rpc(
        app,
        "startWorkbookExport",
        StartWorkbookExportArgs,
        StartWorkbookExportResult,
        start_workbook_export,
    )
    register_rpc(
        app,
        "getWorkbookExportStatus",
        GetWorkbookExportStatusArgs,
        GetWorkbookExportStatusResult,
        get_workbook_export_status,
    )
    register_rpc(
        app,
        "getWorkbookExportResult",
        GetWorkbookExportResultArgs,
        GetWorkbookExportResultResult,
        get_workbook_export_result,
    )
    register_rpc(
        app,
        "cancelWorkbookExport",
        CancelWorkbookExportArgs,
        CancelWorkbookExportResult,
        cancel_workbook_export,
    )
    register_rpc(
        app,
        "startWorkbookImport",
        StartWorkbookImportArgs,
        StartWorkbookImportResult,
        start_workbook_import,
    )
    register_rpc(
        app,
        "getWorkbookImportStatus",
        GetWorkbookImportStatusArgs,
        GetWorkbookImportStatusResult,
        get_workbook_import_status,
    )
    register_rpc(app, "queryDataset", QueryDatasetArgs, QueryDatasetResult, query_dataset)
    register_rpc(
        app,
        "getDatasetFieldValues",
        GetDatasetFieldValuesArgs,
        GetDatasetFieldValuesResult,
        get_dataset_field_values,
    )
    register_rpc(app, "getChartData", GetChartDataArgs, GetChartDataResult, get_chart_data)
